name: Playwright Tests
on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]
jobs:
  playwright:
    name: 'Playwright Tests'
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright/java:v1.39.0-jammy
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        browserName: [chrome, firefox, webkit]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Build & Install
        run: mvn -B install -D skipTests --no-transfer-progress

      - name: Run tests
        run: HOME=/root mvn test -DbrowserName=${{ inputs.browserName }}

      - name: Generate allure report
        run: mvn allure:report

      - name: Archive code coverage results
        if: ${{ always() }}
        uses: actions/upload-artifact@v3
        with:
         name: steamlog-file
         path: steamlogs/*.log

      - name: Archive code coverage results
        if: ${{ always() }}
        uses: actions/upload-artifact@v3
        with:
          name: log-file
          path: logs/*.log

      - name: Archive code coverage results
        if: ${{ always() }}
        uses: actions/upload-artifact@v3
        with:
          name: download-file
          path: downloads/*.exe

      - name: Archive allure report
        if: ${{ always() }}
        uses: actions/upload-artifact@v3
        with:
          name: allure-${{ inputs.browserName }}
          path: target/site